# DJI 9443 Propeller
# https://github.com/byuflowlab/FLOWUnsteady/blob/master/database/rotors/DJI9443.csv
#
#
# Acoustic measurements:
# [1] N. S. Zawodny, D. D. Boyd, and C. L. Burley, “Acoustic Characterization
#     and Prediction of Representative, Small-Scale Rotary-Wing Unmanned
#     Aircraft System Components,” presented at the American Helicopter Society
#     (AHS) Annual Forum, West Palm Beach, FL, May 2016. Accessed: Oct. 27,
#     2023. [Online]. Available: https://ntrs.nasa.gov/citations/20160009054

name: DJI 9443

r_tip: 0.12
r_hub: 0.00624

n_blades: 2
n_radial: 20
n_azimuthal: 60

radial_sampling:
  type: geometric
  ratio_geometric: 0.9
  coeff_conical: 1.0

model:
  inflow: pittpeters
  correction: 
    hubtip: prandtl 
    mach: true 
    rotation: offline

twist:
  values:
    [
      0.2705,
      0.3072,
      0.3267,
      0.3364,
      0.3436,
      0.3455,
      0.3455,
      0.3403,
      0.3325,
      0.3247,
      0.3170,
      0.3066,
      0.2955,
      0.2871,
      0.2787,
      0.2696,
      0.2624,
      0.2540,
      0.2449,
      0.2365,
      0.2281,
      0.2196,
      0.2125,
      0.2041,
      0.1963,
      0.1865,
      0.1781,
      0.1697,
      0.1612,
      0.1541,
      0.1470,
      0.1398,
      0.1327,
      0.1268,
      0.1236,
      0.1191,
      0.1158,
      0.1132,
      0.1119,
      0.1087,
      0.0944,
    ]

  span:
    [
      0.0000,
      0.0254,
      0.0497,
      0.0758,
      0.1001,
      0.1225,
      0.1524,
      0.1748,
      0.1991,
      0.2252,
      0.2495,
      0.2737,
      0.3017,
      0.3241,
      0.3484,
      0.3764,
      0.3988,
      0.4231,
      0.4474,
      0.4735,
      0.4978,
      0.5258,
      0.5482,
      0.5725,
      0.6005,
      0.6247,
      0.6471,
      0.6751,
      0.6994,
      0.7218,
      0.7498,
      0.7741,
      0.7965,
      0.8245,
      0.8488,
      0.8712,
      0.8992,
      0.9235,
      0.9459,
      0.9739,
      1.0000,
    ]

chord:
  values:
    [
      0.0144,
      0.0209,
      0.0260,
      0.0287,
      0.0304,
      0.0316,
      0.0318,
      0.0318,
      0.0312,
      0.0304,
      0.0284,
      0.0263,
      0.0244,
      0.0225,
      0.0208,
      0.0195,
      0.0179,
      0.0165,
      0.0153,
      0.0143,
      0.0134,
      0.0123,
      0.0114,
      0.0107,
      0.0100,
      0.0059,
    ]
  span:
    [
      0.0000,
      0.0413,
      0.0945,
      0.1245,
      0.1478,
      0.1772,
      0.1983,
      0.2010,
      0.2300,
      0.2543,
      0.3076,
      0.3608,
      0.4141,
      0.4674,
      0.5206,
      0.5739,
      0.6272,
      0.6804,
      0.7337,
      0.7869,
      0.8402,
      0.8935,
      0.9467,
      0.9684,
      0.9789,
      1.0000,
    ]

airfoils:
  fnames:
    - /home/hacs/projects/neaptide/Propeller/data/airfoils/dji9443/06.csv
    - /home/hacs/projects/neaptide/Propeller/data/airfoils/dji9443/06.csv
    - /home/hacs/projects/neaptide/Propeller/data/airfoils/dji9443/04.csv
    - /home/hacs/projects/neaptide/Propeller/data/airfoils/dji9443/03.csv
    - /home/hacs/projects/neaptide/Propeller/data/airfoils/dji9443/02.csv
    - /home/hacs/projects/neaptide/Propeller/data/airfoils/dji9443/01.csv
    - /home/hacs/projects/neaptide/Propeller/data/airfoils/dji9443/01.csv
  span:
    - 0.00
    - 0.0857143
    - 0.185714
    - 0.371429
    - 0.714286
    - 0.942857
    - 1.00

polars:
  fnames: # span x Re
    - [ 
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF06_AF06_Re0.010_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF06_AF06_Re0.020_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF06_AF06_Re0.030_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF06_AF06_Re0.050_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF06_AF06_Re0.070_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF06_AF06_Re0.120_M0.10_N9.0_360_V.plr",
      ]
    - [ 
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF06_AF06_Re0.010_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF06_AF06_Re0.020_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF06_AF06_Re0.030_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF06_AF06_Re0.050_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF06_AF06_Re0.070_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF06_AF06_Re0.120_M0.10_N9.0_360_V.plr",
      ]
    - [ 
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF04_AF04_Re0.010_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF04_AF04_Re0.020_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF04_AF04_Re0.030_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF04_AF04_Re0.050_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF04_AF04_Re0.070_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF04_AF04_Re0.120_M0.10_N9.0_360_V.plr",
      ]
    - [ 
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF03_AF03_Re0.010_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF03_AF03_Re0.020_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF03_AF03_Re0.030_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF03_AF03_Re0.050_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF03_AF03_Re0.070_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF03_AF03_Re0.120_M0.10_N9.0_360_V.plr",
      ]
    - [ 
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF02_AF02_Re0.010_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF02_AF02_Re0.020_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF02_AF02_Re0.030_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF02_AF02_Re0.050_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF02_AF02_Re0.070_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF02_AF02_Re0.120_M0.10_N9.0_360_V.plr",
      ]
    - [ 
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF01_AF01_Re0.010_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF01_AF01_Re0.020_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF01_AF01_Re0.030_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF01_AF01_Re0.050_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF01_AF01_Re0.070_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF01_AF01_Re0.120_M0.10_N9.0_360_V.plr",
      ]
    - [ 
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF01_AF01_Re0.010_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF01_AF01_Re0.020_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF01_AF01_Re0.030_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF01_AF01_Re0.050_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF01_AF01_Re0.070_M0.10_N9.0_360_V.plr",
        "/home/hacs/projects/neaptide/Propeller/data/polars/dji9443/AF01_AF01_Re0.120_M0.10_N9.0_360_V.plr",
      ]
  span:
    - 0.00 # AF06
    - 0.0857143 # AF06
    - 0.185714 # AF04
    - 0.371429 # AF03
    - 0.714286 # AF02
    - 0.942857 # AF01
    - 1.00 # AF01

  model:
    enable: false
    stall_transition_rate: 50
    alpha_cutoff: 0.34906585039
    alpha_cl0: 0.03680026727
    cl_a_slope:
      values: [5.359, 5.359]
      span: [0, 1]
